apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-order.fullname" . }}-secret
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Values.postgresql.postgresqlHost .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}