"""init

Revision ID: 417ba7a35da5
Revises: 
Create Date: 2024-01-29 22:12:19.713799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417ba7a35da5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_users_id'), 'users', ['id'], unique=False, schema='billing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_users_id'), table_name='users', schema='billing')
    op.drop_table('users', schema='billing')
    # ### end Alembic commands ###
